### ISSUE TITLE
Make this repository private?

### ISSUE THREAD

**Issue by johnousterhout** [ozensoydc/OS-test#1]
I'm a Professor at Stanford, and I'm teaching an Operating Systems course that uses Pintos for its class projects. I'm writing because an automated search of GitHub identified this repository as possibly containing solutions for the Pintos programming projects. This is a problem for us, because it makes it very easy for students to cheat. Even if they just look at your solution, and don't copy it, that will still reduce the educational experience for them. If this repo does indeed contain Pintos solutions, would you be willing to take it down or at least make it private? If so, that would be a great help to us.

**Comment by ozensoydc** [comment]
Hi, I understand the problem and I would really like to comply, but I only have the most basic git account, and it does not allow for any private repositories at all.  However, none of these are complete solutions, so I guarantee that none of your students can simply look at my and my partner's work in this repo and get a passing grade.

**Comment by johnousterhout** [comment]
Would you be willing to rename the repository so it doesn't have to word
"Pintos" in it? If you do that, then students are unlikely to find it.

**Comment by ozensoydc** [comment]
Done.
